---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: staging-master
  domain: rails-interview.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: background_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sidekiq
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: common
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: whenever
    options: {}
  instance_id: 3217107
  image_type: 2GB
  image_id: 12.04.5 x64
  security_groups:
  - rails_interview_staging_default
  - rails_interview_staging_web
  - rails_interview_staging_staging-master
  - rails_interview_staging_background_worker
  - rails_interview_staging_sidekiq
  - rails_interview_staging_common
  - rails_interview_staging_monit
  - rails_interview_staging_db
  - rails_interview_staging_postgresql
  - rails_interview_staging_postgresql_master
  - rails_interview_staging_nginx
  - rails_interview_staging_redis
  - rails_interview_staging_redis_master
  - rails_interview_staging_unicorn
  - rails_interview_staging_app
  - rails_interview_staging_whenever
  external_host: 
  external_ip: 104.131.203.107
  internal_host: 
  internal_ip: 104.131.203.107
  zone: 
  provider: digital_ocean
  platform: linux
  root_device_type: 
- volumes: {}
  static_ips: {}
